# Generated by Django 4.2.6 on 2023-10-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_exceldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
