# Generated by Django 4.2.6 on 2023-12-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_make_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(unique=True)),
                ('app_name', models.CharField()),
                ('model_name', models.CharField(unique=True)),
                ('public', models.BooleanField(default=False)),
                ('validation_schema', models.JSONField()),
            ],
        ),
    ]
