# Generated by Django 4.2.6 on 2023-12-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('username', models.CharField()),
                ('password', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='modeldata',
            name='foreign_key_app_name',
            field=models.CharField(default='vehicle'),
        ),
        migrations.AddField(
            model_name='modeldata',
            name='foreign_key_model_name',
            field=models.CharField(default='user'),
        ),
        migrations.AlterField(
            model_name='modeldata',
            name='model_name',
            field=models.CharField(),
        ),
    ]
